services:
  - docker:19.03.7-dind

stages:
   - build
   - buildDocker
   - deploy
  
build jar:
  image: maven:latest
  stage: build
  only:
    - master
  script: "mvn package -B -Dmaven.test.skip=true"
  artifacts: 
    paths:
      - bin/*
  tags:
    - and

build docker: 
  image: docker:latest
  stage: buildDocker
  variables:
    DOCKER_HOST: tcp://192.168.1.144:2375
  script:
    - cd bin
    - docker build --force-rm -t registry.cn-qingdao.aliyuncs.com/zhujin/simulatoragv:1.0 .
    - docker tag registry.cn-qingdao.aliyuncs.com/zhujin/simulatoragv:1.0 dudurpg/simulatoragv:1.0
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - docker push dudurpg/simulatoragv:1.0
  dependencies: 
    - build jar
  tags:
    - and
    
deploy: 
  image: docker:latest
  stage: deploy
  variables:
    DOCKER_HOST: tcp://192.168.1.185:2375
  script:
    - docker stop simulatoragv
    - docker rm -f simulatoragv
    - docker run -d -p 15151:15151 --name simulatoragv registry.cn-qingdao.aliyuncs.com/zhujin/simulatoragv:1.0
  dependencies: 
    - build docker
  tags:
    - and
