tcpserver: 
  host: 0.0.0.0
  port: 5151
  heapBuffer: true
  threads:
    processor: 0
  white: 127.0.0.1,192.168.1.102
  
mqtt:
  username: 
  password: 
  host: tcp://192.168.1.221
  clientinid: 1
  topic: tcpserver
  timeout: 1000 
  